name: chall2026-venusian-translator

services:
  venusian-translator:
    image: athack-ctf/chall2026-venusian-translator:latest
    container_name: chall2026-venusian-translator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2026:8000"
