name: chall2026-venusian-translator

services:
  pixcavation:
    image: athack-ctf/chall2026-venusian-translator:latest
    container_name: chall2026-venusian-translator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"